#
# Copyright (c) 2019-2022
# Temmi Pietsch <welcome@temmi.land> & hydrograv GmbH <opensource@hydrograv.com>
#
# This file is part of Liquidium which is released under MIT license.
# See file license.md or go to https://github.com/temmiland/liquidium/ for full license details.
#

FROM couchbase:6.0.4
LABEL maintainer="Temmi Pietsch <welcome@temmi.land>"

ADD config.sh config.sh

ENTRYPOINT ["./config.sh"]
