#
# Copyright (c) 2019-2022
# Tom Pietsch <hello@tomxpcvx.dev> & hydrograv GmbH <opensource@hydrograv.com>
#
# This file is part of Liquidium which is released under MIT license.
# See file license.md or go to https://github.com/tomxpcvx/liquidium/ for full license details.
#

FROM couchbase:6.0.4
LABEL maintainer="Tom Pietsch <t.pietsch@hydrograv.com>"

ADD config.sh config.sh

ENTRYPOINT ["./config.sh"]
